#!/usr/bin/env python3
"""Build the three auditable V24 final-release curve candidates.

The candidates share the reviewed short, medium and xlong Human anchors.  They
only differ at the unresolved 720p15 quality knee.  Every knee is generated by
the same smooth phase/layer risk model and one coupled compute ledger; no
prompt, seed, scene label or output content enters the construction.

This script emits sealed physical blueprints for GPU review and a compact
registry consumed by the final deployment selector.  The registry describes
continuous workload anchors, not an if/else mapping from a request to a
historical version.
"""

from __future__ import annotations

import argparse
from collections import Counter
import json
from pathlib import Path
import sys
from typing import Any


SERVE_ROOT = Path(__file__).resolve().parents[1]
if str(SERVE_ROOT) not in sys.path:
    sys.path.insert(0, str(SERVE_ROOT))

from h3serve.native_engine.planner import (  # noqa: E402
    V19ActionUse,
    V24CurveProfile,
    V24DeploymentSelection,
    V24StrategyVector,
    blueprint_from_runtime_schedule,
    load_v19_candidate_blueprint,
    runtime_schedule_from_blueprint,
    save_v19_candidate_blueprint,
    v19_blueprint_execution_digest,
    v24_strategy_features,
)
from h3serve.native_engine.planner.v24_deployment import (  # noqa: E402
    V24HumanAnchor,
    V24_HUMAN_ANCHORS,
    _CODE_TO_CANONICAL,
    _CANONICAL_RANK,
    _RANK_TO_CANONICAL,
    _compute_units,
    _runtime_action,
    _solve_nested_budget,
)


SCHEMA = "h3_v24_final_release_candidate_registry_v1"
SOURCE_ROOT = (
    SERVE_ROOT / "runtime/pareto/v19_pareto_20260825"
)
V014B = (
    SOURCE_ROOT
    / "versions/v014b_long_quality_shield_core050_terminal025/blueprint.json"
)
ROUND2_TRAJECTORY = (
    SERVE_ROOT
    / "runtime/pareto/v24_curve_learning_20260825/round02/candidates"
    / "v24_curve_preference_r02_r02_720p15_r02_01_trajectory_anchor"
    / "blueprint.json"
)

FINAL_CURVE = V24CurveProfile(
    profile_id="v24_final_contact_peripheral_shield_v1",
    forecast_risk_scale=25.0,
    forecast_run_coupling=0.22,
    opening_amplitude=1.80,
    terminal_amplitude=1.50,
    causal_layer_amplitude=1.20,
    bridge_layer_amplitude=0.70,
)


def _blueprint_state(path: Path) -> tuple[tuple[int, ...], dict[tuple[int, int], str]]:
    blueprint = load_v19_candidate_blueprint(path)
    actual = tuple(sorted({
        step
        for use in blueprint.action_uses
        if isinstance(use, V19ActionUse)
        for step in use.step_indices
    }))
    runtime = {
        (step, layer): action
        for step, layer, action in runtime_schedule_from_blueprint(blueprint)
        if step in set(actual)
    }
    expected = {(step, layer) for step in actual for layer in range(50)}
    if set(runtime) != expected:
        raise ValueError(f"blueprint does not cover every Actual cell: {path}")
    return actual, runtime


def _code(action: str) -> str:
    canonical = action.rsplit(":", 1)[-1]
    symbol = {
        "sparse_topk_0.0625": "S",
        "sparse_topk_0.1": "T",
        "sparse_topk_0.25": "Q",
        "sparse_topk_0.5": "H",
        "dense": "D",
    }[canonical]
    if ":" in action and action.rsplit(":", 1)[0] == "frontier":
        symbol = symbol.lower()
    return symbol


def _rows(
    actual: tuple[int, ...],
    runtime: dict[tuple[int, int], str],
) -> tuple[tuple[int, str], ...]:
    return tuple(
        (step, "".join(_code(runtime[(step, layer)]) for layer in range(50)))
        for step in actual
    )


def _temporary_anchor(
    *,
    anchor_id: str,
    actual: tuple[int, ...],
    runtime: dict[tuple[int, int], str],
    source_digest: str,
) -> V24HumanAnchor:
    return V24HumanAnchor(
        anchor_id=anchor_id,
        video_tokens=98_440,
        rows=_rows(actual, runtime),
        source_execution_digest=source_digest,
        artifact_sha256=("0" * 64,),
        evidence=("final release proposal; Human continuous playback required",),
    )


def _synthetic_round2_floor() -> V24HumanAnchor:
    actual, _runtime = _blueprint_state(ROUND2_TRAJECTORY)
    # Preserve the Human-observed stable correction placement while allowing
    # the coupled optimizer to buy Attention fidelity where it has the largest
    # modeled contact/peripheral benefit.
    rows = tuple((step, "s" * 50) for step in actual)
    source = json.loads(ROUND2_TRAJECTORY.read_text(encoding="utf-8"))
    return V24HumanAnchor(
        anchor_id="round2_stable_trajectory_sparse_floor",
        video_tokens=98_440,
        rows=rows,
        source_execution_digest=str(source["execution_digest"]),
        artifact_sha256=("0" * 64,),
        evidence=(
            "Human: Round2 720p15 had no dynamic background anomaly",
            "Only its correction placement is retained; Attention is re-solved",
        ),
    )


def _selection_at_budget(
    anchor: V24HumanAnchor,
    *,
    target_compute_units: float,
) -> tuple[V24DeploymentSelection, dict[str, Any]]:
    actual, state, optimizer = _solve_nested_budget(
        total_steps=20,
        lower=anchor,
        upper=anchor,
        mix=0.0,
        endpoint=anchor.actual_steps,
        mandatory_actual=(),
        target_compute_units=target_compute_units,
        forecast_risk_multiplier=FINAL_CURVE.forecast_risk_scale,
        curve=FINAL_CURVE,
    )
    endpoint = set(anchor.actual_steps)
    actual_set = set(actual)
    runtime: list[tuple[int, int, str]] = []
    for step in range(20):
        if step not in actual_set:
            runtime.extend(
                (step, layer, "forecastfrontier:sparse_topk_0.0625")
                for layer in range(3)
            )
            continue
        for layer in range(50):
            rank, prefix = (
                state[(step, layer)] if step in endpoint else (4, None)
            )
            runtime.append((step, layer, _runtime_action(rank, prefix)))
    schedule = tuple(runtime)
    selection = V24DeploymentSelection(
        actual_step_indices=actual,
        attention_action_schedule=schedule,
        summary={
            "execution_profile_hint": None,
            "estimated_compute_units": optimizer["achieved_compute_units"],
        },
    )
    return selection, optimizer


def _anchor_selection(anchor: V24HumanAnchor) -> V24DeploymentSelection:
    runtime = []
    actual = set(anchor.actual_steps)
    for step in range(20):
        if step not in actual:
            runtime.extend(
                (step, layer, "forecastfrontier:sparse_topk_0.0625")
                for layer in range(3)
            )
            continue
        row = dict(anchor.rows)[step]
        for layer, code in enumerate(row):
            canonical = _CODE_TO_CANONICAL[code]
            prefix = None if canonical == "dense" else (
                "forecastfrontier" if code.isupper() else "frontier"
            )
            runtime.append((step, layer, _runtime_action(
                _CANONICAL_RANK[canonical], prefix
            )))
    return V24DeploymentSelection(
        actual_step_indices=anchor.actual_steps,
        attention_action_schedule=tuple(runtime),
        summary={"execution_profile_hint": None},
    )


def _write_candidate(
    root: Path,
    *,
    candidate_id: str,
    selection: V24DeploymentSelection,
    role: str,
    optimizer: dict[str, Any] | None = None,
) -> dict[str, Any]:
    candidate_root = root / "candidates" / candidate_id
    candidate_root.mkdir(parents=True, exist_ok=True)
    blueprint = blueprint_from_runtime_schedule(
        candidate_id=candidate_id,
        total_steps=20,
        actual_step_indices=selection.actual_step_indices,
        attention_action_schedule=selection.attention_action_schedule,
        source="v24_final_release_curve_candidate_v1",
    )
    blueprint_path = candidate_root / "blueprint.json"
    save_v19_candidate_blueprint(blueprint_path, blueprint)
    vector = V24StrategyVector.from_selection(selection, total_steps=20)
    features = v24_strategy_features(vector)
    actual = set(selection.actual_step_indices)
    counts = Counter(
        action.rsplit(":", 1)[-1]
        for step, _layer, action in selection.attention_action_schedule
        if step in actual
    )
    document = {
        "schema_version": SCHEMA,
        "candidate_id": candidate_id,
        "role": role,
        "curve_profile": FINAL_CURVE.to_dict(),
        "actual_step_indices": list(selection.actual_step_indices),
        "forecast_step_indices": [
            step for step in range(20) if step not in actual
        ],
        "actual_attention_cells": dict(sorted(counts.items())),
        "estimated_compute_units": features["compute_ratio"] * 20.0,
        "estimated_compute_ratio": features["compute_ratio"],
        "features": features,
        "strategy": vector.to_dict(include_flat_vectors=False),
        "strategy_digest": vector.digest,
        "execution_digest": v19_blueprint_execution_digest(blueprint),
        # Keep release metadata relocatable.  The benchmark loader resolves
        # registry entries relative to the registry itself, so an absolute
        # DrvFS path would make the sealed bundle machine-specific.
        "blueprint": blueprint_path.relative_to(root).as_posix(),
        "optimizer": optimizer,
        "prompt_semantics_used": False,
        "claim_scope": (
            "versioned calibration candidate; final release status is recorded "
            "in final_decision.json"
        ),
    }
    (candidate_root / "plan.json").write_text(
        json.dumps(document, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    return document


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output-root", type=Path, required=True)
    args = parser.parse_args()
    root = args.output_root.resolve()
    root.mkdir(parents=True, exist_ok=True)

    v014b_actual, v014b_runtime = _blueprint_state(V014B)
    v014b_document = json.loads(V014B.read_text(encoding="utf-8"))
    v014b_anchor = _temporary_anchor(
        anchor_id="v014b_contact_peripheral_upgrade_floor",
        actual=v014b_actual,
        runtime=v014b_runtime,
        source_digest=str(v014b_document["execution_digest"]),
    )
    round2_floor = _synthetic_round2_floor()

    definitions = (
        (
            "v24_final_c01_v014b_shield_u7p00",
            v014b_anchor,
            7.00,
            "V014b correction trajectory plus learned contact/peripheral fidelity upgrades",
        ),
        (
            "v24_final_c02_round2_trajectory_u7p00",
            round2_floor,
            7.00,
            "Round2 background-stable correction trajectory at the matched compute budget",
        ),
        (
            "v24_final_c03_round2_trajectory_u7p30",
            round2_floor,
            7.30,
            "Round2 background-stable trajectory with additional small-object/peripheral fidelity",
        ),
    )
    candidates: list[dict[str, Any]] = []
    for candidate_id, anchor, target, role in definitions:
        selection, optimizer = _selection_at_budget(
            anchor,
            target_compute_units=target,
        )
        candidates.append(_write_candidate(
            root,
            candidate_id=candidate_id,
            selection=selection,
            role=role,
            optimizer=optimizer,
        ))

    shared = {}
    for role, anchor_id in (
        ("short_knee", "short_34k_v007_quality"),
        ("medium_knee", "medium_66k_v022_causal"),
        ("xlong_knee", "xlong_218k_v012_v018_exact"),
    ):
        anchor = next(
            value for value in V24_HUMAN_ANCHORS
            if value.anchor_id == anchor_id
        )
        row = _write_candidate(
            root,
            candidate_id=f"v24_final_shared_{role}",
            selection=_anchor_selection(anchor),
            role=f"shared reviewed {role}",
        )
        shared[role] = row

    registry = {
        "schema_version": SCHEMA,
        "curve_profile": FINAL_CURVE.to_dict(),
        "public_quality_knee_acceleration": 75.0,
        "public_aggressive_endpoint_acceleration": 100.0,
        "release_decision": {
            "status": "human_review_complete",
            "default_candidate": "v24_final_c02_round2_trajectory_u7p00",
            "production_surface_is_immutable": True,
            "historical_comparator": "v24_final_stable_v009",
            "decision_artifact": "final_decision.json",
        },
        "shared_anchors": {
            key: {
                "candidate_id": value["candidate_id"],
                "video_tokens": next(
                    anchor.video_tokens
                    for anchor in V24_HUMAN_ANCHORS
                    if (
                        (key == "short_knee" and anchor.anchor_id.startswith("short_"))
                        or (key == "medium_knee" and anchor.anchor_id.startswith("medium_"))
                        or (key == "xlong_knee" and anchor.anchor_id.startswith("xlong_"))
                    )
                ),
                "execution_digest": value["execution_digest"],
                "strategy": value["strategy"],
            }
            for key, value in shared.items()
        },
        "release_candidates": [
            {
                "candidate_id": row["candidate_id"],
                "long_knee_video_tokens": 98_440,
                "execution_digest": row["execution_digest"],
                "estimated_compute_units": row["estimated_compute_units"],
                "strategy": row["strategy"],
                "blueprint": row["blueprint"],
            }
            for row in candidates
        ],
        "invariants": {
            "prompt_semantics_used": False,
            "public_controls": ["sampling_steps", "acceleration"],
            "maximum_forecast_run": 3,
            "quality_knee_is_human_constrained": True,
            "acceleration_100_is_explicitly_aggressive": True,
        },
    }
    registry_path = root / "candidate_registry.json"
    registry_path.write_text(
        json.dumps(registry, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    manifest = {
        "schema_version": 1,
        "purpose": "V24 final 720p15 Human review candidates",
        "candidates": [
            {"name": row["candidate_id"], "blueprint": row["blueprint"]}
            for row in candidates
        ],
    }
    manifest_path = root / "720p15_blueprints.json"
    manifest_path.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(json.dumps({
        "registry": str(registry_path),
        "720p15_manifest": str(manifest_path),
        "candidates": [
            {
                "candidate_id": row["candidate_id"],
                "estimated_compute_units": row["estimated_compute_units"],
                "actual_step_indices": row["actual_step_indices"],
                "actual_attention_cells": row["actual_attention_cells"],
                "execution_digest": row["execution_digest"],
            }
            for row in candidates
        ],
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
